<template>
  <div ref="chartContainer" style="width: 100%; height: 600px;"></div>
</template>

<script setup>
import { useI18n } from 'vue-i18n';
import { ref, onMounted, onUnmounted, markRaw } from 'vue';
import * as echarts from 'echarts';

const { t } = useI18n();
const chartContainer = ref(null);
let chart = null;

// 原始数据
const objectData = {
  rigid: [
{ name: 'plate', value: 33621 },
{ name: 'box', value: 25955 },
{ name: 'cup', value: 17974 },
{ name: 'basket', value: 16027 },
{ name: 'bread', value: 12230 },
{ name: 'bowl', value: 12087 },
{ name: 'spoon', value: 9540 },
{ name: 'peach', value: 9527 },
{ name: 'parts', value: 9490 },
{ name: 'cola', value: 9233 },
{ name: 'orange', value: 8696 },
{ name: 'banana', value: 8135 },
{ name: 'clothes', value: 7317 },
{ name: 'pen', value: 7274 },
{ name: 'shelf', value: 6725 },
{ name: 'milk', value: 6551 },
{ name: 'egg yolk p', value: 6458 },
{ name: 'card', value: 6069 },
{ name: 'sensor', value: 6069 },
{ name: 'conveyor b', value: 6034 },
{ name: 'long bread', value: 5500 },
{ name: 'pot lid', value: 5433 },
{ name: 'glasses', value: 5376 },
{ name: 'sprite', value: 5302 },
{ name: 'steamer', value: 5240 },
{ name: 'sliced bre', value: 5043 },
{ name: 'eraser', value: 5034 },
{ name: 'beverage', value: 4839 },
{ name: 'block', value: 4810 },
{ name: 'bottle', value: 4397 },
{ name: 'cestbon', value: 4121 },
{ name: 'baozi', value: 4040 },
{ name: 'snack', value: 3999 },
{ name: 'cheese', value: 3777 },
{ name: 'lettuce', value: 3777 },
{ name: 'tomato sli', value: 3777 },
{ name: 'meat pie', value: 3777 },
{ name: 'glass', value: 3707 },
{ name: 'coffee cap', value: 3701 },
{ name: 'apple', value: 3531 },
{ name: 'pen holder', value: 3517 },
{ name: 'egg', value: 3500 },
{ name: 'coffee', value: 3471 },
{ name: 'dish', value: 3439 },
{ name: 'tape', value: 3312 },
{ name: 'rubiks cub', value: 3296 },
{ name: 'yogurt', value: 3295 },
{ name: 'duck', value: 3200 },
{ name: 'gum', value: 3200 },
{ name: 'detergent', value: 3200 },
{ name: 'bath ball', value: 3200 },
{ name: 'chocolate', value: 3200 },
{ name: 'egg beater', value: 3200 },
{ name: 'hard clean', value: 3200 },
{ name: 'soft clean', value: 3200 },
{ name: 'bread slic', value: 3200 },
{ name: 'soda', value: 3200 },
{ name: 'soap', value: 3200 },
{ name: 'brush', value: 3200 },
{ name: 'can', value: 3200 },
{ name: 'lime', value: 3200 },
{ name: 'marker', value: 3200 },
{ name: 'chips', value: 3200 },
{ name: 'peeler', value: 3200 },
{ name: 'power stri', value: 3200 },
{ name: 'cookie', value: 3200 },
{ name: 'part', value: 3186 },
{ name: 'carton', value: 3113 },
{ name: 'bag', value: 2866 },
{ name: 'paper cup', value: 2859 },
{ name: 'test tube', value: 2729 },
{ name: 'test tube ', value: 2729 },
{ name: 'hanger', value: 2723 },
{ name: 'trash can', value: 2709 },
{ name: 'transparen', value: 2620 },
{ name: 'red wine', value: 2620 },
{ name: 'NFC orange', value: 2620 },
{ name: 'black mug', value: 2620 },
{ name: 'orange jui', value: 2582 },
{ name: 'book', value: 2309 },
{ name: 'cleaner', value: 2261 },
{ name: 'pear', value: 2200 },
{ name: 'building b', value: 2146 },
{ name: 'water', value: 1938 },
{ name: 'scissor', value: 1834 },
{ name: 'ruler', value: 1834 },
{ name: 'mouse', value: 1801 },
{ name: 'battery', value: 1772 },
{ name: 'plate rack', value: 1701 },
{ name: 'pot', value: 1695 },
{ name: 'plastic', value: 1673 },
{ name: 'fruit plat', value: 1673 },
{ name: 'glue', value: 1673 },
{ name: 'art knife', value: 1673 },
{ name: 'knife', value: 1621 },
{ name: 'coaster', value: 1601 },
{ name: 'paper box', value: 1554 },
{ name: 'tray', value: 1524 },
{ name: 'parcel', value: 1519 },
{ name: 'green tea', value: 1501 },
{ name: 'yili chang', value: 1501 },
{ name: 'meinianda', value: 1501 },
{ name: 'master kon', value: 1501 },
{ name: 'lemon', value: 1493 },
{ name: 'zipper', value: 1441 },
{ name: 'food bag', value: 1441 },
{ name: 'teapot', value: 1423 },
{ name: 'switch but', value: 1406 },
{ name: 'egg carton', value: 1406 },
{ name: 'grape', value: 1403 },
{ name: 'building b', value: 1360 },
{ name: 'mango', value: 1347 },
{ name: 'rice', value: 1309 },
{ name: 'chopsticks', value: 1306 },
{ name: 'bookshelf', value: 1288 },
{ name: 'wahaha min', value: 1266 },
{ name: 'nongfu spr', value: 1266 },
{ name: 'yibao mine', value: 1266 },
{ name: 'baisui mou', value: 1266 },
{ name: 'ham sausag', value: 1266 },
{ name: 'sponge', value: 1242 },
{ name: 'ball', value: 1224 },
{ name: 'cake', value: 1222 },
{ name: 'desk lamp', value: 1196 },
{ name: 'pallet', value: 1196 },
{ name: 'teacup', value: 1068 },
{ name: 'mouse box', value: 1039 },
{ name: 'shoes', value: 1009 },
{ name: 'blackboard', value: 999 },
{ name: 'blackboard', value: 999 },
{ name: 'document b', value: 985 },
{ name: 'fork', value: 947 },
{ name: 'black cont', value: 897 },
{ name: 'pomegranat', value: 873 },
{ name: 'cube block', value: 859 },
{ name: 'cup rack', value: 834 },
{ name: 'power bank', value: 828 },
{ name: 'tea', value: 823 },
{ name: 'storage bo', value: 815 },
{ name: 'broom', value: 813 },
{ name: 'rice cooke', value: 809 },
{ name: 'pruple rag', value: 801 },
{ name: 'blue rag', value: 801 },
{ name: 'pen cap', value: 758 },
{ name: 'toy car', value: 740 },
{ name: 'tape measu', value: 740 },
{ name: 'mineral wa', value: 739 },
{ name: 'mineral wa', value: 739 },
{ name: 'grain cup', value: 727 },
{ name: 'empty bott', value: 703 },
{ name: 'five in on', value: 703 },
{ name: 'dustbin', value: 703 },
{ name: 'model', value: 703 },
{ name: 'lamp', value: 703 },
{ name: 'computer b', value: 703 },
{ name: 'frying pan', value: 690 },
{ name: 'umbrella', value: 690 },
{ name: 'snacks', value: 690 },
{ name: 'steel fram', value: 690 },
{ name: 'shark dagg', value: 690 },
{ name: 'dryer', value: 686 },
{ name: 'lunch box', value: 670 },
{ name: 'cucumber', value: 662 },
{ name: 'bread mach', value: 649 },
{ name: 'fruit', value: 649 },
{ name: 'button', value: 612 },
{ name: 'fake banan', value: 606 },
{ name: 'plastic ve', value: 606 },
{ name: 'knife hold', value: 606 },
{ name: 'donut', value: 601 },
{ name: 'table tenn', value: 600 },
{ name: 'vegetables', value: 600 },
{ name: 'lid', value: 600 },
{ name: 'shoe rack', value: 600 },
{ name: 'headphones', value: 600 },
{ name: 'screwdrive', value: 600 },
{ name: 'scissors', value: 600 },
{ name: 'blocks', value: 569 },
{ name: 'glass lid', value: 507 },
{ name: 'yellow bas', value: 507 },
{ name: 'brown bask', value: 507 },
{ name: 'red cup', value: 507 },
{ name: 'handbag', value: 507 },
{ name: 'gray cup', value: 507 },
{ name: 'coffee bea', value: 507 },
{ name: 'pink spoon', value: 507 },
{ name: 'blue spoon', value: 507 },
{ name: 'coffee mac', value: 501 },
{ name: 'cup lid', value: 500 },
{ name: 'coffee bea', value: 500 },
{ name: 'rice scoop', value: 500 },
{ name: 'rice conta', value: 500 },
{ name: 'plug', value: 460 },
{ name: 'socket', value: 460 },
{ name: 'egg box', value: 420 },
{ name: 'sink', value: 413 },
{ name: 'pumpkin', value: 411 },
{ name: 'washing ma', value: 409 },
{ name: 'doll', value: 408 },
{ name: 'accessorie', value: 407 },
{ name: 'water cup', value: 379 },
{ name: 'water bott', value: 377 },
{ name: 'pliers', value: 350 },
{ name: 'eyeglass c', value: 349 },
{ name: 'kettle', value: 349 },
{ name: 'calculator', value: 338 },
{ name: 'bed', value: 331 },
{ name: 'graphics c', value: 314 },
{ name: 'ice cream', value: 309 },
{ name: 'storage bi', value: 307 },
{ name: 'potato', value: 307 },
{ name: 'seasonings', value: 303 },
{ name: 'storage ra', value: 303 },
{ name: 'headphone ', value: 300 },
{ name: '9', value: 300 },
{ name: 'shoebox', value: 300 },
{ name: 'erase', value: 300 },
{ name: 'coffee sta', value: 300 },
{ name: 'pointed-no', value: 300 },
{ name: 'pencil cas', value: 300 },
{ name: 'pen contai', value: 300 },
{ name: 'chair', value: 290 },
{ name: 'garbage bi', value: 289 },
{ name: 'washbasin', value: 267 },
{ name: 'rabbit dol', value: 266 },
{ name: 'swiss roll', value: 249 },
{ name: 'shark doll', value: 249 },
{ name: 'small basi', value: 249 },
{ name: 'building b', value: 246 },
{ name: 'toy circle', value: 246 },
{ name: 'floor', value: 241 },
{ name: 'vitamin b ', value: 212 },
{ name: 'tea bag', value: 212 },
{ name: 'toilet', value: 210 },
{ name: 'toilet bru', value: 200 },
{ name: 'toilet bru', value: 200 },
{ name: 'triangle b', value: 200 },
{ name: 'bear doll', value: 200 },
{ name: 'bluetooth ', value: 199 },
{ name: 'bluetooth ', value: 199 },
{ name: 'cube-shape', value: 199 },
{ name: 'cube', value: 199 },
{ name: 'magnet', value: 199 },
{ name: 'little dog', value: 199 },
{ name: 'cone', value: 199 },
{ name: 'basin', value: 199 },
{ name: 'paper', value: 199 },
{ name: 'cone-shape', value: 199 },
{ name: 'sphere', value: 199 },
{ name: 'sphere-sha', value: 199 },
{ name: 'small cube', value: 195 },
{ name: 'bucket', value: 188 },
{ name: 'nightstand', value: 178 },
{ name: 'cable', value: 174 },
{ name: 'compartmen', value: 172 },
{ name: 'fruit tray', value: 161 },
{ name: 'pencil sha', value: 161 },
{ name: 'colored gl', value: 161 },
{ name: 'small piec', value: 161 },
{ name: 'waste pape', value: 161 },
{ name: 'water disp', value: 151 },
{ name: 'chili pepp', value: 150 },
{ name: 'hair dryer', value: 147 },
{ name: 'square', value: 147 },
{ name: 'trash can ', value: 137 },
{ name: 'router', value: 125 },
{ name: 'tool', value: 123 },
{ name: 'furniturei', value: 118 },
{ name: 'microwave', value: 117 },
{ name: 'french fri', value: 117 },
{ name: 'central ai', value: 115 },
{ name: 'toiletries', value: 115 },
{ name: 'portable p', value: 112 },
{ name: 'solid beve', value: 112 },
{ name: 'slippers', value: 111 },
{ name: 'shoe cabin', value: 111 },
{ name: 'tea table', value: 110 },
{ name: 'dustpan', value: 110 },
{ name: 'stove', value: 109 },
{ name: 'groove', value: 106 },
{ name: 'dishwashin', value: 104 },
{ name: 'trash bin', value: 102 },
{ name: 'tableware ', value: 101 },
{ name: 'steamer ca', value: 101 },
{ name: 'steamer li', value: 101 },
{ name: 'green doll', value: 101 },
{ name: 'blue doll', value: 101 },
{ name: 'pillow', value: 101 },
{ name: 'beef', value: 100 },
{ name: 'bluetooth ', value: 100 },
{ name: 'energy dri', value: 100 },
{ name: 'toilet cle', value: 100 },
{ name: 'bluetooth ', value: 100 },
{ name: 'towel', value: 100 },
{ name: 'pentagonal', value: 100 },
{ name: 'cone groov', value: 100 },
{ name: 'pentagonal', value: 100 },
{ name: 'cube-shape', value: 100 },
{ name: 'cone block', value: 100 },
{ name: 'spherical ', value: 100 },
{ name: 'cube groov', value: 100 },
{ name: 'marker pen', value: 100 },
{ name: 'square pyr', value: 100 },
{ name: 'tag', value: 100 },
{ name: 'door handl', value: 100 },
{ name: 'triangular', value: 100 },
{ name: 'glass cup', value: 100 },
{ name: 'bulb', value: 100 },
{ name: 'fanta', value: 100 },
{ name: 'gold bar', value: 100 },
{ name: 'syringe', value: 99 },
{ name: 'drawer', value: 99 },
{ name: 'poster', value: 99 },
{ name: 'dishwasher', value: 98 },
{ name: 'cutting bo', value: 98 },
{ name: 'beverage b', value: 98 },
{ name: 'mosquito r', value: 96 },
{ name: 'freezer', value: 95 },
{ name: 'ceramic cu', value: 95 },
{ name: 'pan', value: 95 },
{ name: 'charging p', value: 90 },
{ name: 'sandbag', value: 86 },
{ name: 'rack', value: 85 },
{ name: 'tap', value: 82 },
{ name: 'boil the k', value: 78 },
{ name: 'heating pl', value: 78 },
{ name: 'stove top', value: 78 },
{ name: 'tissue', value: 77 },
{ name: 'remote con', value: 77 },
{ name: 'barrel', value: 72 },
{ name: 'microwave ', value: 65 },
{ name: 'coffee cup', value: 63 },
{ name: 'prawns', value: 60 },
{ name: 'braised po', value: 60 },
{ name: 'wooden fra', value: 60 },
{ name: 'grid', value: 60 },
{ name: 'green pepp', value: 59 },
{ name: 'tools', value: 54 },
{ name: 'biscuit', value: 50 },
{ name: 'notebook', value: 50 },
{ name: 'hand tappi', value: 50 },
{ name: 'small bowl', value: 50 },
{ name: 'utility kn', value: 50 },
{ name: 'milk carto', value: 50 },
{ name: 'meinian da', value: 50 },
{ name: 'long-nose ', value: 50 },
{ name: 'little gui', value: 50 },
{ name: 'medicine b', value: 50 },
{ name: 'computer', value: 50 },
{ name: 'paper lid ', value: 50 },
{ name: 'mobile pho', value: 50 },
{ name: 'mini table', value: 50 },
{ name: 'beer mug', value: 50 },
{ name: 'car', value: 50 },
{ name: 'double-sid', value: 50 },
{ name: 'disk', value: 50 },
{ name: 'diamond', value: 50 },
{ name: 'hot water ', value: 49 },
{ name: 'meat', value: 49 },
{ name: 'network sw', value: 49 },
{ name: 'cubicle', value: 49 },
{ name: 'remote con', value: 49 },
{ name: 'eggs', value: 49 },
{ name: 'circular t', value: 48 },
{ name: 'measuring ', value: 44 },
{ name: 'palte', value: 13 },
{ name: 'pillows', value: 10 },
{ name: 'apple tree', value: 10 },
  ],
  hinge: [
{ name: 'cabinet', value: 9275 },
{ name: 'glasses ca', value: 8277 },
{ name: 'faucet', value: 3134 },
{ name: 'lid', value: 3009 },
{ name: 'shoe box', value: 2818 },
{ name: 'drawer', value: 907 },
{ name: 'parts', value: 547 },
{ name: 'refrigerat', value: 261 },
{ name: 'the door', value: 213 },
{ name: 'storage bo', value: 115 },
{ name: 'cabinet do', value: 95 },
  ],
  deformable: [
{ name: 'clothes', value: 38151 },
{ name: 'towel', value: 8485 },
{ name: 'parcel', value: 4405 },
{ name: 'steamer', value: 3283 },
{ name: 'baozi', value: 2691 },
{ name: 'data cable', value: 2214 },
{ name: 'paper ball', value: 1834 },
{ name: 'shirt', value: 1762 },
{ name: 'rag', value: 1053 },
{ name: 'beauty ble', value: 990 },
{ name: 'shorts', value: 987 },
{ name: 'tissue pap', value: 903 },
{ name: 'bannana', value: 703 },
{ name: 'shoe', value: 703 },
{ name: 'white carr', value: 603 },
{ name: 'eggplant', value: 603 },
{ name: 'long sleev', value: 599 },
{ name: 'shoe rack', value: 599 },
{ name: 'shoes', value: 599 },
{ name: 'snack', value: 594 },
{ name: 'beverage', value: 594 },
{ name: 'flowers', value: 592 },
{ name: 'vase', value: 592 },
{ name: 'dumplings', value: 592 },
{ name: 'croissant', value: 570 },
{ name: 'stain', value: 503 },
{ name: 'coffee', value: 500 },
{ name: 'pants', value: 500 },
{ name: 'dryer', value: 425 },
{ name: 'cookies', value: 350 },
{ name: 'water', value: 321 },
{ name: 'plate', value: 303 },
{ name: 'potato chi', value: 300 },
{ name: 'chip box', value: 300 },
{ name: 'cookie box', value: 300 },
{ name: 'tissues', value: 250 },
{ name: 'wet wipes', value: 240 },
{ name: 'plastic sh', value: 161 },
{ name: 'green pepp', value: 153 },
{ name: 'potato', value: 153 },
{ name: 'trash bag', value: 137 },
{ name: 'foam clean', value: 130 },
{ name: 'carpet', value: 130 },
{ name: 'leftovers', value: 128 },
{ name: 'cloth', value: 126 },
{ name: 'garbage ba', value: 113 },
{ name: 'cloth bag', value: 112 },
{ name: 'mineral wa', value: 112 },
{ name: 't shirt', value: 112 },
{ name: 'disposable', value: 112 },
{ name: 'roll paper', value: 112 },
{ name: 'clotheslin', value: 110 },
{ name: 'clothes ha', value: 110 },
{ name: 'blanket', value: 101 },
{ name: 'quilt', value: 101 },
{ name: 'toothpaste', value: 101 },
{ name: 'comb', value: 101 },
{ name: 'toothbrush', value: 101 },
{ name: 'pink doll', value: 101 },
{ name: 'curtains', value: 99 },
{ name: 'wet tissue', value: 98 },
{ name: 'stains', value: 98 },
{ name: 'clothes ba', value: 96 },
{ name: 'garbage', value: 82 },
{ name: 'chopped sc', value: 82 },
{ name: 'bed sheet', value: 77 },
{ name: 'pillow', value: 50 },
{ name: 'square pla', value: 50 },
{ name: 'platform', value: 48 },
{ name: 'peache', value: 48 },
{ name: 'network ca', value: 46 },
{ name: 'sofa', value: 10 },
{ name: 'fruit', value: 1 },
{ name: 'tissue pap', value: 1 },
{ name: 'vegetable ', value: 1 },
  ]
};

// 处理数据：分别按值降序排序，并提取名称和数值数组
const processData = () => {
  const sortedRigid = [...objectData.rigid].sort((a, b) => b.value - a.value);
  const sortedHinge = [...objectData.hinge].sort((a, b) => b.value - a.value);
  const sortedDeformable = [...objectData.deformable].sort((a, b) => b.value - a.value);

  return {
    rigidCategories: sortedRigid.map(item => item.name),
    rigidValues: sortedRigid.map(item => item.value),
    hingeCategories: sortedHinge.map(item => item.name),
    hingeValues: sortedHinge.map(item => item.value),
    deformableCategories: sortedDeformable.map(item => item.name),
    deformableValues: sortedDeformable.map(item => item.value)
  };
};

const initChart = () => {
  if (!chartContainer.value) return;
  
  chart = markRaw(echarts.init(chartContainer.value));
  const { rigidCategories, rigidValues, hingeCategories, hingeValues, deformableCategories, deformableValues } = processData();

  const option = {
    title: {
      left: 'center',
      textStyle: { fontSize: 16 }
    },
    tooltip: {
      trigger: 'axis',
      axisPointer: { type: 'shadow' }
    },
    // 关键配置：定义左右两个图表区域
    grid: [
      { // 左侧网格（低协作图表）
        left: '0%',
        right: '0%', // 左侧图表占据约一半少一点的空间，为中间留出间隙
        top: '5%',
        bottom: '52%',
        containLabel: true
      },
      {
        left: '0%',
        right: '84%',
        top: '52%',
        bottom: '15%',
        containLabel: true
      },
      {
        left: '16%',
        right: '0%',
        top: '52%',
        bottom: '15%',
        containLabel: true
      }
    ],
    yAxis: [
      { // 左侧x轴
        type: 'log',
        gridIndex: 0, // 关联到第一个grid
        position: 'bottom'
      },
      { // 右侧x轴
        type: 'log',
        gridIndex: 1, // 关联到第二个grid
        position: 'bottom'
      },
      { // 右侧x轴
        type: 'log',
        gridIndex: 2, // 关联到第二个grid
        position: 'bottom'
      }
    ],
    xAxis: [
      { // 左侧y轴（低协作动作名称）
        type: 'category',
        gridIndex: 0,
        name: t('highlights.task.object.rigid'),
        nameLocation: 'middle',
        nameGap: 80,
        data: rigidCategories,
        axisLabel: { color: '#9edfa0', rotate: 90 },
      },
      { // 右侧y轴（高协作动作名称）
        type: 'category',
        gridIndex: 1,
        name: t('highlights.task.object.hinged'),
        nameLocation: 'middle',
        nameGap: 80,
        data: hingeCategories,
        axisLabel: { color: '#91cc75', rotate: 90 },
      },
      { // 右侧y轴（高协作动作名称）
        type: 'category',
        gridIndex: 2,
        name: t('highlights.task.object.deformable'),
        nameLocation: 'middle',
        nameGap: 80,
        data: deformableCategories,
        axisLabel: { color: '#70965e', rotate: 90 },
      }
    ],
    series: [
      {
        name: t('highlights.task.object.rigid'),
        type: 'bar',
        xAxisIndex: 0,
        yAxisIndex: 0,
        data: rigidValues,
        itemStyle: { color: '#9edfa0' },
      },
      {
        name: t('highlights.task.object.hinged'),
        type: 'bar',
        xAxisIndex: 1,
        yAxisIndex: 1,
        data: hingeValues,
        itemStyle: { color: '#91cc75' },
      },
      {
        name: t('highlights.task.object.deformable'),
        type: 'bar',
        xAxisIndex: 2,
        yAxisIndex: 2,
        data: deformableValues,
        itemStyle: { color: '#70965e' },
      }
    ]
  };

  chart.setOption(option);
};

const handleResize = () => {
  if (chart) chart.resize();
};

onMounted(() => {
  initChart();
  window.addEventListener('resize', handleResize);
});

onUnmounted(() => {
  if (chart) chart.dispose();
  window.removeEventListener('resize', handleResize);
});
</script>